### ISSUE TITLE
La sección de CUDA no se puede abrir

### ISSUE THREAD

**Issue by mixcoha** [uibcdf/Academia#10]
Hola Diego.
La sección de CUDA no puede ser desplegada. ¿Sabes si ha sido cambiada o borrada?
Gracias =D

**Comment by dprada** [comment]
Estoy con eso ahora. Estaba por concluir. En un ratito la termino XD

**Comment by dprada** [comment]
La de Linux la tengo que corregir, como el resto... pero ya he terminado hoy todo su contenido.

**Comment by dprada** [comment]
Ya está la primera versión del notebook de CUDA. Gracias por notar que no estaba!
